/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleTABLA12;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        for(int i = 0; i <= 12; i++)
        {
            System.out.print("12 * "+ i + " = " + 12 * i + "\n");
        }
    }
}
